name: Node.js Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Node.js
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Turbo
        run: npm i -g turbo@latest

      - name: Install Dependencies
        run: npm ci --production

      - name: Build & Lint
        run: turbo build lint
